### ISSUE TITLE
Front-end Tracking Issue

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Curtin-Motorsport-Team/datalogger#2]
This is a tracking issue for the browser front-end.

General tasks to do:

- [ ] Set up the build chain so we can transpile a basic React app, bundle everything using webpack (or browserify, or whatever), embed the assets in the binary using `Go.Rice`, then serve some dummy hello world page
- [ ] Add a configuration page 
   - [ ]  update the config file on the fly
- [ ] Serve a subset of the data
- [ ] Make pretty charts using `charts.io`
- [ ] Add the ability to change which data points are displayed, and a slider to alter the start and end times

**Comment by Michael-F-Bryan** [comment]
Created the basic shell app and set up the build chain so everything *Just Works*.
